### ISSUE TITLE
Large discussion around the direction of the project

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-test-helpers#100]
I've seen a few PRs now that are moving to creating/using internal kepler services. Is this the direction the project is moving? if so why? My concern on my end is that I don't want the bloat in my environments. I don't see why we need to introduce more complexity to this project by adding kepler services. I always saw this project as a light weight dll to help developers get integration testing not an all in one solution. Is this project moving to that? again if so why?

**Comment by jake-martin** [comment]
David, our goal is to make Test Helpers fully compatible with RelativityOne, not to make it an all-in-one solution. There were a few helpers that used DBContext to run direct SQL queries, which is not possible in RelativityOne. Rather than remove these methods entirely, we are replacing their implementation with Kepler endpoints (comprised of two .dlls), which is the recommended best practice. We're also utilizing the Kepler framework that has been available to the public since version 10.3.191.8. In the future, we are going to create a Kepler library that is separate from Test Helpers.

This current version of Test Helpers is still a work in progress, and we will be adding additional functionality to ensure that it still has backwards compatibility with older version of Relativity (i.e. dynamically check whether to use Kepler).

We apologize for not communicating this information better, and we can make time for further discussion if you would like.

**Comment by dvbarnes** [comment]
Jake,

Thank you for clarifying the reasoning here. For more context, we do run our integration tests against a few environments to help us understand how our code will run in different versions. One thing I do get worried about with the kepler addition is the overhead/maintenance of installing these services. For example, if an install fails now all my tests fail (even if I'm not using that function). For RelativityOne is using the vpn not an option? Relativity has been very helpful in not only setting up a vpn to run tests, but also allowing us to setup a vm in our azure environment so we can now run these using our CI/CD servers.

**Comment by ppande1020** [comment]
Hey David,

Running tests with the VPN is an option but we did not want to be dependent on it. This is because we have a tonne of ISV's who use our sandbox to run their tests and using VPN to run them adds complexity to their test execution cycle. Although it can be an overkill, Kepler is the standard for interacting with the database, especially since we are moving away from sql helpers, The team is working on making sure that the helpers are updated, so the tests dont fail on a failed install.

We are internally discussing if we should pull out these Kepler helpers into its own library and get the dev community to build on that. This could potentially happen if we know there is a demand from the community for this need.

I hope this helps. 

-Priya

**Comment by dvbarnes** [comment]
@ppande1020 I like that idea to pull out the kepler helpers mostly because then it keeps this one clean, in cases where you may not need/want them.

Thanks, all for the insight.
