### ISSUE TITLE
Make native path configurable in the ImportAPI Helper

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-test-helpers#5]
I would like to make a change to the [Import API helpers](https://github.com/relativitydev/relativity-test-helpers/blob/master/Source/Relativity.Test.Helpers/Relativity.Test.Helpers/ImportAPIHelper/ImportAPIHelper.cs) allowing the native name to be configurable. Before I do this I have a few asks:

1) What is the use case Relativity has with this file?
     - I'm specifically asking to allow the "\\\\FakeFilePath\Natives\SampleTextFile.txt" to be injected as a function parameter and not be hard coded.

**Comment by ppande1020** [comment]
I was pretty much using this helper to import a few documents in my workspace. I didnt really care about the native that was being imported for these documents since I was only looking to test the metadata. Hardcoding this was probably not a good idea and so you are welcome to make this change and inject this as a function parameter so users could pass the location of their native file, when they call this function.

**Comment by dvbarnes** [comment]
No worries, I have created a branch and made the changes, unfortunately it looks as if I do not have the permissions to push my new branch. I have a feeling this will be an issue with any new developers wanting to join, can you look into solving this?

**Comment by dvbarnes** [comment]
#6

**Comment by ppande1020** [comment]
I can make you a contributor to this project so you can make updates as and when needed. If there are breaking changes, let's create an issue and discuss it here since we have a few projects that depend on Relativity Test Helpers. Thank again!

**Comment by dvbarnes** [comment]
No worries, I think the recommended workflow is what I did to get things in. As a side note when can I expect this to be added?

**Comment by ppande1020** [comment]
The Nuget package is up. Please check v1.3 - https://www.nuget.org/packages/RelativityTestHelpersNuget/

**Comment by dvbarnes** [comment]
Thanks
